### ISSUE TITLE
Unity Import won't take v1.4

### ISSUE THREAD

**Issue by ModischFabrications** [JanikHelbig/TinyContainer#1]
Seems like v1.3 is the only one that's imported, there might be an issue somewhere with the Release?

Included using `"com.jnk.tinycontainer": "https://github.com/JanikHelbig/TinyContainer.git?path=Assets/TinyContainer#1.4.0",`

**Comment by JanikHelbig** [comment]
Fixed in v1.4.1, this was simply a issue with the meta data in `package.json`. You should functionally have the latest verion.
